const initialState = [
  {
    id: 1,
    category: "Article",
    title: "Boost your conversion rate",
    author: "Learn with sumit",
    date: "11 Jul, 2022·6 min read",
    img: "https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80",
  },
  {
    id: 2,
    category: "Personal",
    title: "How to use search engine optimization to drive sales",
    author: "Raton",
    date: "11 Jul, 2022·6 min read",
    img: "https://image.shutterstock.com/image-photo/businessman-using-mobile-smart-phone-260nw-1932042689.jpg",
  },
  {
    id: 3,
    category: "Personal",
    title: "Improve your customer experience",
    author: "Onoy",
    date: "11 Jul, 2022·6 min read",
    img: "https://images.unsplash.com/photo-1547586696-ea22b4d4235d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80",
  },
  {
    id: 4,
    category: "Article",
    title: "How to activate Hulu ?",
    author: "Learn with sumit",
    date: "11 Jul, 2022·6 min read",
    img: "https://img.lovepik.com/photo/50055/9941.jpg_wh300.jpg",
  },
  {
    id: 5,
    category: "Technical",
    title: "How to Activate Telemundo",
    author: "Raton",
    date: "11 Jul, 2022·6 min read",
    img: "https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80",
  },
  {
    id: 6,
    category: "Technical",
    title: "Can I get Amazon Music on Roku?",
    author: "Onoy",
    date: "11 Jul, 2022·6 min read",
    img: "https://www.bryair.com/wp-content/uploads/2021/12/technology-image.jpg",
  },
  {
    id: 7,
    category: "Music",
    title: "How to play MOV files on Windows 10",
    author: "Rubel",
    date: "11 Jul, 2022·6 min read",
    img: "https://image.shutterstock.com/image-photo/businessman-using-mobile-smart-phone-260nw-1932042689.jpg",
  },
  {
    id: 8,
    category: "Music",
    title: "Is Peacock available on PS4?",
    author: "Onoy",
    date: "11 Jul, 2022·6 min read",
    img: "https://images.unsplash.com/photo-1547586696-ea22b4d4235d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80",
  },
  {
    id: 9,
    category: "Music",
    title: "Where to Enter Amazon Registration Code?",
    author: "Rubel",
    date: "11 Jul, 2022·6 min read",
    img: "https://www.bryair.com/wp-content/uploads/2021/12/technology-image.jpg",
  },
];

export default initialState;
